### ISSUE TITLE
v0.3 release

### ISSUE THREAD

**Issue by k82cn** [kubernetes-retired/kube-batch#512]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

Trace all related tasks for v0.3 release.

**Tasks**:

- [x] Build docker images
- [x] Update tutorial & helm charts (https://github.com/kubernetes-sigs/kube-batch/pull/517)
- [x] Update changelogs (https://github.com/kubernetes-sigs/kube-batch/pull/518)
