### ISSUE TITLE
Add phase/conditions into PodGroup.Status

### ISSUE THREAD

**Issue by k82cn** [kubernetes-retired/kube-batch#521]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

Currently, kube-batch only raised `Unschedulable` event for its status; it's better to include phase and conditions in `PodGroup.Status` to give more detail.

**Tasks**

- [x] Design Doc (https://github.com/kubernetes-sigs/kube-batch/pull/533)
- [x] Add phase/condition into `PodGroup.Status` CRD (https://github.com/kubernetes-sigs/kube-batch/pull/525)
- [x] Updated phase/condition by `kube-batch` (https://github.com/kubernetes-sigs/kube-batch/pull/560)

**Comment by Zyqsempai** [comment]
@k82cn I would like to work on this one, but can you please provide more details.
As far as I can see, currently we have that type of status for `PodGroup`:
https://github.com/kubernetes-sigs/kube-batch/blob/master/pkg/apis/scheduling/v1alpha1/types.go#L50
You want to extend `PodGroupStatus` struct and add few fields for additional info?

**Comment by k82cn** [comment]
> You want to extend PodGroupStatus struct and add few fields for additional info?

Yes, we need to add `PodGroupPhase` and `Conditions` at least; so the operator/controller knows where it is in its lifecycle. We can refer to PodStatus :)

**Comment by Zyqsempai** [comment]
Got it, I will take care of it!

**Comment by Zyqsempai** [comment]
@k82cn Hey, so I opened PR, but I still have some questions, I am not sure how and where we will fill up those new fields, also, I created them based on same Pod.Status fields, not sure that every value is acceptable for PodGroup.

**Comment by k82cn** [comment]
>I am not sure how and where we will fill up those new fields

kube batch will update after each scheduling cycle.

**Comment by Zyqsempai** [comment]
@k82cn , Great, will be happy to work on it, but what about original PR, should we merge it, or wait for related PR based on your design doc?

**Comment by k82cn** [comment]
> but what about original PR, should we merge it, 

For your PR, I think that's a good start; I'll also add some comments according to the design doc. So I'd suggest to update your PR when design doc is ready. I'll try to get doc ready this week and ask you and @Jeffwan to review

**Comment by Jeffwan** [comment]
@k82cn I think for short term, I will only update podCondition for those pods that fails in predicate action. If that case, cluster autoscaler will scale up right count of new nodes. It would be great to see your doc and work on long term support.

**Comment by k82cn** [comment]
@Zyqsempai , would you help to update your PRs according to https://github.com/kubernetes-sigs/kube-batch/blob/master/doc/design/podgroup-status.md :)

**Comment by k82cn** [comment]
> I think for short term, I will only update podCondition for those pods that fails in predicate action. If that case, cluster autoscaler will scale up right count of new nodes. 

I'm ok with that; we can cover regular case firstly. For gang-scheduling/coscheduling case, we'll discuss it later :)

**Comment by Zyqsempai** [comment]
@k82cn Done;)

**Comment by k82cn** [comment]
@Zyqsempai , are you going to work on the other items, e.g. updating status accordingly? If not, someone from our team may help on it :)

**Comment by Zyqsempai** [comment]
@k82cn Will be glad to, can you point me a little bit? I can't find the proper place where status should be updated.
